# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        # the name of the "filter set"
        big_slide:
            quality: 90
            filters:
                thumbnail: { size: [374, 374], mode: outbound }
                background: { size: [374, 374], position: center, color: '#fff' }
        small_slide:
          quality: 90
          filters:
            thumbnail: { size: [185, 185], mode: outbound }
            background: { size: [185, 185], position: center, color: '#fff' }
        header_photo:
          quality: 90
          filters:
            thumbnail: { size: [55, 55], mode: outbound }
            background: { size: [55, 55], position: center, color: '#fff' }
        my_tour_logo:
          quality: 90
          filters:
            thumbnail: { size: [134, 107], mode: outbound }
            background: { size: [134, 107], position: center, color: '#fff' }
        tour_card:
          quality: 90
          filters:
            upscale: { min: [350, 550] }
            thumbnail: { size: [350, 550], mode: outbound }
            background: { size: [350, 550], position: center, color: '#fff' }
