vich_uploader:
    db_driver: orm

    mappings:
        upload_images:
            uri_prefix: '%app.path.upload_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.upload_images%'
            namer: vich_uploader.namer_uniqid